akka {
  coordinated-shutdown.run-by-jvm-shutdown-hook=off
}

cors {
  allowed-origins = ["*"]
  allowed-methods = ["GET", "POST", "PUT", "DELETE", "HEAD", "OPTIONS"]
  allowed-headers = ["*"]
  allow-credentials = false
  max-age = 0
}