(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_01 (t : string) : option string :=
  match t with
  | "BigIntObject" => Some "OrdinaryObject"
  | "BigUint64Array" => Some "TypedArray"
  | "BooleanObject" => Some "OrdinaryObject"
  | "BoundFunctionExoticObject" => Some "ExoticObject"
  | "BreakCompletion" => Some "AbruptCompletion"
  | "BuiltinFunctionObject" => Some "OrdinaryObject"
  | "Constructor" => Some "FunctionObject"
  | "ContinueCompletion" => Some "AbruptCompletion"
  | _ => None
  end.
