(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_05 (t : string) : option string :=
  match t with
  | "Iterator" => Some "Object"
  | "Map" => Some "OrdinaryObject"
  | "ModuleEnvironmentRecord" => Some "DeclarativeEnvironmentRecord"
  | "ModuleNamespaceExoticObject" => Some "ExoticObject"
  | "MutableBinding" => Some "Binding"
  | "NormalCompletion" => Some "CompletionRecord"
  | "NumberObject" => Some "OrdinaryObject"
  | "ObjectEnvironmentRecord" => Some "EnvironmentRecord"
  | _ => None
  end.
