(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String ZArith List.
Import ListNotations.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_own_bindings_chunk_07 (t : string) : option (list record_field_binding) :=
  match t with
  | "Int8Array" => Some ((mkRecordFieldBinding "ContentType" false (RFCEnum ("number" :: nil))) :: (mkRecordFieldBinding "TypedArrayName" false (RFCStrSet (((73%Z) :: (110%Z) :: (116%Z) :: (56%Z) :: (65%Z) :: (114%Z) :: (114%Z) :: (97%Z) :: (121%Z) :: nil) :: nil))) :: nil)
  | "IteratorRecord" => Some ((mkRecordFieldBinding "Done" false (RFCBool true true)) :: (mkRecordFieldBinding "Iterator" false (RFCRecord (("Object", nil) :: nil))) :: (mkRecordFieldBinding "NextMethod" false (RFCUnion ((RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil)) :: RFCNumber :: RFCBigInt :: RFCStr :: (RFCBool true true) :: RFCUndef :: RFCNull :: nil))) :: nil)
  | "JobCallbackRecord" => Some ((mkRecordFieldBinding "Callback" false (RFCRecord (("Object", (("Call", (false, RFCAny)) :: nil)) :: nil))) :: (mkRecordFieldBinding "HostDefined" false (RFCEnum ("empty" :: nil))) :: nil)
  | "JobRecord" => Some ((mkRecordFieldBinding "Job" false RFCClo) :: (mkRecordFieldBinding "Realm" false (RFCRecord (("RealmRecord", nil) :: nil))) :: (mkRecordFieldBinding "ScriptOrModule" false (RFCRecord (("ModuleRecord", nil) :: ("ScriptRecord", nil) :: nil))) :: nil)
  | "LoadedModuleRequestRecord" => Some ((mkRecordFieldBinding "Attributes" false (RFCList (RFCRecord (("ImportAttributeRecord", nil) :: nil)))) :: (mkRecordFieldBinding "Module" false (RFCRecord (("ModuleRecord", nil) :: nil))) :: (mkRecordFieldBinding "Specifier" false RFCStr) :: nil)
  | "Map" => Some ((mkRecordFieldBinding "MapData" false (RFCList (RFCRecord (("", (("Key", (false, (RFCUnion ((RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil)) :: (RFCEnum ("empty" :: nil)) :: RFCNumber :: RFCBigInt :: RFCStr :: (RFCBool true true) :: RFCUndef :: RFCNull :: nil)))) :: ("Value", (false, (RFCUnion ((RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil)) :: RFCNumber :: RFCBigInt :: RFCStr :: (RFCBool true true) :: RFCUndef :: RFCNull :: nil)))) :: nil)) :: nil)))) :: nil)
  | "MatchRecord" => Some ((mkRecordFieldBinding "EndIndex" false (RFCMathIntSign false true true)) :: (mkRecordFieldBinding "StartIndex" false (RFCMathIntSign false true true)) :: nil)
  | "ModuleEnvironmentRecord" => Some ((mkRecordFieldBinding "CreateImportBinding" false (RFCCloNames ("Record[ModuleEnvironmentRecord].CreateImportBinding" :: nil))) :: (mkRecordFieldBinding "GetBindingValue" false (RFCCloNames ("Record[ModuleEnvironmentRecord].GetBindingValue" :: nil))) :: (mkRecordFieldBinding "GetThisBinding" false (RFCCloNames ("Record[ModuleEnvironmentRecord].GetThisBinding" :: nil))) :: (mkRecordFieldBinding "HasThisBinding" false (RFCCloNames ("Record[ModuleEnvironmentRecord].HasThisBinding" :: nil))) :: nil)
  | _ => None
  end.
