(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_00 (t : string) : option string :=
  match t with
  | "AbruptCompletion" => Some "CompletionRecord"
  | "ArgumentsExoticObject" => Some "ExoticObject"
  | "Array" => Some "ExoticObject"
  | "ArrayBuffer" => Some "Object"
  | "ArrayIteratorInstance" => Some "OrdinaryObject"
  | "AsyncFromSyncIterator" => Some "OrdinaryObject"
  | "AsyncGenerator" => Some "OrdinaryObject"
  | "BigInt64Array" => Some "TypedArray"
  | _ => None
  end.
