(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_04 (t : string) : option string :=
  match t with
  | "GeneratorExecutionContext" => Some "ExecutionContext"
  | "GlobalEnvironmentRecord" => Some "EnvironmentRecord"
  | "IdentifierReferenceRecord" => Some "ReferenceRecord"
  | "ImmutableBinding" => Some "Binding"
  | "ImmutablePrototypeExoticObject" => Some "ExoticObject"
  | "Int16Array" => Some "TypedArray"
  | "Int32Array" => Some "TypedArray"
  | "Int8Array" => Some "TypedArray"
  | _ => None
  end.
