(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_06 (t : string) : option string :=
  match t with
  | "OrdinaryObject" => Some "Object"
  | "PendingPromise" => Some "Promise"
  | "PrivateReferenceRecord" => Some "ReferenceRecord"
  | "Promise" => Some "OrdinaryObject"
  | "PromiseAllResolveElementFunction" => Some "BuiltinFunctionObject"
  | "PropertyReferenceRecord" => Some "ReferenceRecord"
  | "ProxyExoticObject" => Some "ExoticObject"
  | "RegExp" => Some "OrdinaryObject"
  | _ => None
  end.
