(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_02 (t : string) : option string :=
  match t with
  | "CyclicModuleRecord" => Some "ModuleRecord"
  | "DataView" => Some "OrdinaryObject"
  | "Date" => Some "OrdinaryObject"
  | "DeclarativeEnvironmentRecord" => Some "EnvironmentRecord"
  | "ECMAScriptCodeExecutionContext" => Some "ExecutionContext"
  | "ECMAScriptFunctionObject" => Some "OrdinaryObject"
  | "ErrorObject" => Some "OrdinaryObject"
  | "ExoticObject" => Some "Object"
  | _ => None
  end.
