(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String ZArith List.
Import ListNotations.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_own_bindings_chunk_13 (t : string) : option (list record_field_binding) :=
  match t with
  | "Uint8Array" => Some ((mkRecordFieldBinding "ContentType" false (RFCEnum ("number" :: nil))) :: (mkRecordFieldBinding "TypedArrayName" false (RFCStrSet (((85%Z) :: (105%Z) :: (110%Z) :: (116%Z) :: (56%Z) :: (65%Z) :: (114%Z) :: (114%Z) :: (97%Z) :: (121%Z) :: nil) :: nil))) :: nil)
  | "Uint8ClampedArray" => Some ((mkRecordFieldBinding "ContentType" false (RFCEnum ("number" :: nil))) :: (mkRecordFieldBinding "TypedArrayName" false (RFCStrSet (((85%Z) :: (105%Z) :: (110%Z) :: (116%Z) :: (56%Z) :: (67%Z) :: (108%Z) :: (97%Z) :: (109%Z) :: (112%Z) :: (101%Z) :: (100%Z) :: (65%Z) :: (114%Z) :: (114%Z) :: (97%Z) :: (121%Z) :: nil) :: nil))) :: nil)
  | "UnresolvableReferenceRecord" => Some ((mkRecordFieldBinding "Base" false (RFCEnum ("unresolvable" :: nil))) :: (mkRecordFieldBinding "ReferencedName" false RFCStr) :: nil)
  | "WeakMap" => Some ((mkRecordFieldBinding "WeakMapData" false (RFCList (RFCRecord (("", (("Key", (false, (RFCUnion ((RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil)) :: (RFCEnum ("empty" :: nil)) :: RFCNumber :: RFCBigInt :: RFCStr :: (RFCBool true true) :: RFCUndef :: RFCNull :: nil)))) :: ("Value", (false, (RFCUnion ((RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil)) :: RFCNumber :: RFCBigInt :: RFCStr :: (RFCBool true true) :: RFCUndef :: RFCNull :: nil)))) :: nil)) :: nil)))) :: nil)
  | "WeakRef" => Some ((mkRecordFieldBinding "WeakRefTarget" false (RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil))) :: nil)
  | "WeakSet" => Some ((mkRecordFieldBinding "WeakSetData" false (RFCList (RFCUnion ((RFCRecord (("Object", nil) :: ("Symbol", nil) :: nil)) :: RFCNumber :: RFCBigInt :: RFCStr :: (RFCBool true true) :: RFCUndef :: RFCNull :: nil)))) :: nil)
  | _ => None
  end.
