(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_03 (t : string) : option string :=
  match t with
  | "FinalizationRegistry" => Some "OrdinaryObject"
  | "Float16Array" => Some "TypedArray"
  | "Float32Array" => Some "TypedArray"
  | "Float64Array" => Some "TypedArray"
  | "ForInIterator" => Some "OrdinaryObject"
  | "FunctionEnvironmentRecord" => Some "DeclarativeEnvironmentRecord"
  | "FunctionObject" => Some "Object"
  | "Generator" => Some "OrdinaryObject"
  | _ => None
  end.
