(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_08 (t : string) : option string :=
  match t with
  | "ThrowCompletion" => Some "AbruptCompletion"
  | "TypedArray" => Some "ExoticObject"
  | "Uint16Array" => Some "TypedArray"
  | "Uint32Array" => Some "TypedArray"
  | "Uint8Array" => Some "TypedArray"
  | "Uint8ClampedArray" => Some "TypedArray"
  | "UnresolvableReferenceRecord" => Some "ReferenceRecord"
  | "WeakMap" => Some "OrdinaryObject"
  | _ => None
  end.
