(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_09 (t : string) : option string :=
  match t with
  | "WeakRef" => Some "OrdinaryObject"
  | "WeakSet" => Some "OrdinaryObject"
  | _ => None
  end.
