(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String ZArith List.
Import ListNotations.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_own_bindings_chunk_02 (t : string) : option (list record_field_binding) :=
  match t with
  | "BreakCompletion" => Some ((mkRecordFieldBinding "Target" false (RFCUnion ((RFCEnum ("empty" :: nil)) :: RFCStr :: nil))) :: (mkRecordFieldBinding "Type" false (RFCEnum ("break" :: nil))) :: (mkRecordFieldBinding "Value" false (RFCEnum ("empty" :: nil))) :: nil)
  | "BuiltinFunctionObject" => Some ((mkRecordFieldBinding "Call" false (RFCCloNames ("Record[BuiltinFunctionObject].Call" :: nil))) :: (mkRecordFieldBinding "Construct" true (RFCCloNames ("Record[BuiltinFunctionObject].Construct" :: nil))) :: (mkRecordFieldBinding "InitialName" false (RFCUnion (RFCStr :: RFCNull :: nil))) :: (mkRecordFieldBinding "Realm" false (RFCRecord (("RealmRecord", nil) :: nil))) :: (mkRecordFieldBinding "__CODE__" false RFCClo) :: nil)
  | "CandidateExecutionRecord" => Some ((mkRecordFieldBinding "ChosenValues" false (RFCList (RFCRecord (("ChosenValueRecord", nil) :: nil)))) :: (mkRecordFieldBinding "EventsRecords" false (RFCList (RFCRecord (("AgentEventsRecord", nil) :: nil)))) :: nil)
  | "ChosenValueRecord" => Some ((mkRecordFieldBinding "ChosenValue" false (RFCList (RFCMathIntSign true true true))) :: (mkRecordFieldBinding "Event" false (RFCRecord (("SharedDataBlockEvent", nil) :: nil))) :: nil)
  | "ClassFieldDefinitionRecord" => Some ((mkRecordFieldBinding "Initializer" false (RFCUnion ((RFCRecord (("ECMAScriptFunctionObject", nil) :: nil)) :: (RFCEnum ("empty" :: nil)) :: nil))) :: (mkRecordFieldBinding "Name" false (RFCUnion ((RFCRecord (("PrivateName", nil) :: ("Symbol", nil) :: nil)) :: RFCStr :: nil))) :: nil)
  | "ClassStaticBlockDefinitionRecord" => Some ((mkRecordFieldBinding "BodyFunction" false (RFCRecord (("Object", (("Call", (false, RFCAny)) :: nil)) :: nil))) :: nil)
  | "CompletionRecord" => Some ((mkRecordFieldBinding "Target" false (RFCUnion ((RFCEnum ("empty" :: nil)) :: RFCStr :: nil))) :: (mkRecordFieldBinding "Type" false (RFCEnum ("break" :: "continue" :: "normal" :: "return" :: "throw" :: nil))) :: (mkRecordFieldBinding "Value" false RFCAny) :: nil)
  | "Constructor" => Some ((mkRecordFieldBinding "Construct" false RFCAny) :: nil)
  | _ => None
  end.
