(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String ZArith List.
Import ListNotations.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_own_bindings_chunk_06 (t : string) : option (list record_field_binding) :=
  match t with
  | "GraphLoadingStateRecord" => Some ((mkRecordFieldBinding "HostDefined" false (RFCEnum ("empty" :: nil))) :: (mkRecordFieldBinding "IsLoading" false (RFCBool true true)) :: (mkRecordFieldBinding "PendingModulesCount" false (RFCMathIntSign false true true)) :: (mkRecordFieldBinding "PromiseCapability" false (RFCRecord (("PromiseCapabilityRecord", nil) :: nil))) :: (mkRecordFieldBinding "Visited" false (RFCList (RFCRecord (("CyclicModuleRecord", nil) :: nil)))) :: nil)
  | "IdentifierReferenceRecord" => Some ((mkRecordFieldBinding "Base" false (RFCRecord (("EnvironmentRecord", nil) :: nil))) :: (mkRecordFieldBinding "ReferencedName" false RFCStr) :: nil)
  | "ImmutableBinding" => Some ((mkRecordFieldBinding "__MUTABLE__" false (RFCBool true false)) :: (mkRecordFieldBinding "__STRICT__" false (RFCBool true true)) :: nil)
  | "ImmutablePrototypeExoticObject" => Some ((mkRecordFieldBinding "DefineOwnProperty" false (RFCCloNames ("Record[OrdinaryObject].DefineOwnProperty" :: nil))) :: (mkRecordFieldBinding "Delete" false (RFCCloNames ("Record[OrdinaryObject].Delete" :: nil))) :: (mkRecordFieldBinding "Get" false (RFCCloNames ("Record[OrdinaryObject].Get" :: nil))) :: (mkRecordFieldBinding "GetOwnProperty" false (RFCCloNames ("Record[OrdinaryObject].GetOwnProperty" :: nil))) :: (mkRecordFieldBinding "GetPrototypeOf" false (RFCCloNames ("Record[OrdinaryObject].GetPrototypeOf" :: nil))) :: (mkRecordFieldBinding "HasProperty" false (RFCCloNames ("Record[OrdinaryObject].HasProperty" :: nil))) :: (mkRecordFieldBinding "IsExtensible" false (RFCCloNames ("Record[OrdinaryObject].IsExtensible" :: nil))) :: (mkRecordFieldBinding "OwnPropertyKeys" false (RFCCloNames ("Record[OrdinaryObject].OwnPropertyKeys" :: nil))) :: (mkRecordFieldBinding "PreventExtensions" false (RFCCloNames ("Record[OrdinaryObject].PreventExtensions" :: nil))) :: (mkRecordFieldBinding "Set" false (RFCCloNames ("Record[OrdinaryObject].Set" :: nil))) :: (mkRecordFieldBinding "SetPrototypeOf" false (RFCCloNames ("Record[ImmutablePrototypeExoticObject].SetPrototypeOf" :: nil))) :: nil)
  | "ImportAttributeRecord" => Some ((mkRecordFieldBinding "Key" false RFCStr) :: (mkRecordFieldBinding "Value" false RFCStr) :: nil)
  | "ImportEntryRecord" => Some ((mkRecordFieldBinding "ImportName" false (RFCUnion ((RFCEnum ("namespace-object" :: nil)) :: RFCStr :: nil))) :: (mkRecordFieldBinding "LocalName" false RFCStr) :: (mkRecordFieldBinding "ModuleRequest" false (RFCRecord (("ModuleRequestRecord", nil) :: nil))) :: nil)
  | "Int16Array" => Some ((mkRecordFieldBinding "ContentType" false (RFCEnum ("number" :: nil))) :: (mkRecordFieldBinding "TypedArrayName" false (RFCStrSet (((73%Z) :: (110%Z) :: (116%Z) :: (49%Z) :: (54%Z) :: (65%Z) :: (114%Z) :: (114%Z) :: (97%Z) :: (121%Z) :: nil) :: nil))) :: nil)
  | "Int32Array" => Some ((mkRecordFieldBinding "ContentType" false (RFCEnum ("number" :: nil))) :: (mkRecordFieldBinding "TypedArrayName" false (RFCStrSet (((73%Z) :: (110%Z) :: (116%Z) :: (51%Z) :: (50%Z) :: (65%Z) :: (114%Z) :: (114%Z) :: (97%Z) :: (121%Z) :: nil) :: nil))) :: nil)
  | _ => None
  end.
