(** GENERATED by [esmeta.fv.FVTyModel] — DO NOT EDIT. *)
From Stdlib Require Import String.
From ESMetaFV Require Import TyModelBase.
Local Open Scope string_scope.

Definition record_parent_chunk_07 (t : string) : option string :=
  match t with
  | "ReturnCompletion" => Some "AbruptCompletion"
  | "Set" => Some "OrdinaryObject"
  | "SettledPromise" => Some "Promise"
  | "SharedArrayBuffer" => Some "Object"
  | "SourceTextModuleRecord" => Some "CyclicModuleRecord"
  | "StringExoticObject" => Some "ExoticObject"
  | "SuperReferenceRecord" => Some "ReferenceRecord"
  | "SymbolObject" => Some "OrdinaryObject"
  | _ => None
  end.
