import importlib.util
import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock


RUNNER = Path(__file__).parents[1] / "run-test262-full.py"
SPEC = importlib.util.spec_from_file_location("run_test262_full", RUNNER)
runner = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(runner)


class RunTest262FullTest(unittest.TestCase):
    def write_generated_semantic_fixture(self, root):
        formal = root / "formal"
        formal.mkdir(parents=True, exist_ok=True)
        (formal / "_CoqProject").write_text(
            "unrelated-proof.v\n"
            f"{runner.TYMODEL_BLOCK_START}\n"
            "TyModelBase.v\n"
            "TyModelParent00.v\n"
            "TyModelBindings00.v\n"
            "TyModel.v\n"
            f"{runner.TYMODEL_BLOCK_END}\n",
            encoding="utf-8",
        )
        (formal / "TyModelBase.v").write_text(
            "Definition base := 1.\n", encoding="utf-8"
        )
        (formal / "TyModelParent00.v").write_text(
            "Definition parent := 1.\n", encoding="utf-8"
        )
        (formal / "TyModelBindings00.v").write_text(
            "Definition bindings := 1.\n", encoding="utf-8"
        )
        (formal / "TyModel.v").write_text(
            "From ESMetaFV Require Import TyModelBase.\n"
            "From ESMetaFV Require Import TyModelParent00.\n"
            "From ESMetaFV Require Import TyModelBindings00.\n",
            encoding="utf-8",
        )

        spec_dir = formal / "validation" / "spec"
        spec_dir.mkdir(parents=True, exist_ok=True)
        spec_entries = [
            "validation/spec/SpecFuncs.v",
            "validation/spec/SpecFuncs_0000.v",
            "validation/spec/SpecGlobals.v",
            "validation/spec/SpecHeap.v",
            "validation/spec/SpecHeap_0000.v",
        ]
        (formal / "validation" / "SpecSources.mk").write_text(
            "# AUTO-GENERATED by FVInitState; do not edit.\n"
            "SPEC_GENERATED_SOURCES := \\\n"
            + "\n".join(
                f"  {entry}{' \\' if index + 1 < len(spec_entries) else ''}"
                for index, entry in enumerate(spec_entries)
            )
            + "\n",
            encoding="utf-8",
        )
        for entry in spec_entries:
            (formal / entry).write_text(
                f"(* {Path(entry).name} *)\n", encoding="utf-8"
            )
        (spec_dir / "SpecFuncs.v").write_text(
            "From ESMetaFV.validation.spec Require Export SpecFuncs_0000.\n",
            encoding="utf-8",
        )
        (spec_dir / "SpecHeap.v").write_text(
            "From ESMetaFV.validation.spec Require Export SpecHeap_0000.\n",
            encoding="utf-8",
        )
        (formal / "validation" / "Spec.v").write_text(
            "From ESMetaFV Require Import validation.spec.SpecFuncs.\n",
            encoding="utf-8",
        )

    def test_pending_ranges_do_not_include_completed_global_indices(self):
        pool = [
            runner.Target(0, 10, "a.js"),
            runner.Target(1, 11, "b.js"),
            runner.Target(2, 12, "c.js"),
            runner.Target(3, 13, "d.js"),
        ]

        ranges = runner.pending_ranges(pool, {11}, shard_size=2)

        self.assertEqual(
            [[target.global_index for target in group] for group in ranges],
            [[10], [12, 13]],
        )

    def test_driver_pass_is_classified_as_pass(self):
        output = "T000      0.123s        456  PASS               language/a.js\n"

        status, reason = runner.classify_driver_output(
            output, 0, "T000", "language/a.js"
        )

        self.assertEqual((status, reason), ("PASS", ""))

    def test_driver_nonzero_exit_cannot_be_classified_as_pass(self):
        output = "T000      0.123s        456  PASS               language/a.js\n"

        status, reason = runner.classify_driver_output(
            output, 1, "T000", "language/a.js"
        )

        self.assertEqual(status, "BUILD_ERROR")
        self.assertIn("PASS", reason)

    def test_driver_result_difference_is_classified_as_mismatch(self):
        output = (
            "T000      0.123s        456  RESULT-DIFFERS     "
            "language/a.js (VBool vs VUndef)\n"
        )

        status, reason = runner.classify_driver_output(
            output, 0, "T000", "language/a.js"
        )

        self.assertEqual(status, "MISMATCH")
        self.assertIn("RESULT-DIFFERS", reason)

    def test_driver_ast_alias_difference_is_classified_as_mismatch(self):
        output = (
            "T000      0.123s        456  AST-ALIASES-DIFFER "
            "language/a.js\n"
        )

        status, reason = runner.classify_driver_output(
            output, 0, "T000", "language/a.js"
        )

        self.assertEqual(status, "MISMATCH")
        self.assertIn("AST-ALIASES-DIFFER", reason)

    def test_driver_unsupported_effect_is_classified_as_unsupported(self):
        output = (
            "T000      0.123s        456  UNSUPPORTED-EFFECT  "
            "Choose; Fn <- Script; marker language/a.js\n"
        )

        status, reason = runner.classify_driver_output(
            output, 0, "T000", "language/a.js"
        )

        self.assertEqual(status, "UNSUPPORTED")
        self.assertIn("UNSUPPORTED-EFFECT", reason)

    def test_driver_crash_is_not_misclassified_as_build_error(self):
        output = (
            "T000      0.123s        456  CRASH Failure(x) language/a.js\n"
        )

        status, reason = runner.classify_driver_output(
            output, 0, "T000", "language/a.js"
        )

        self.assertEqual(status, "CRASH")
        self.assertIn("CRASH", reason)

    def test_driver_verdict_identity_must_match_selected_test(self):
        wrong_id = "T999 0.123s 456 PASS language/a.js\n"
        wrong_name = "T000 0.123s 456 PASS language/other.js\n"

        for output in (wrong_id, wrong_name):
            with self.subTest(output=output):
                status, reason = runner.classify_driver_output(
                    output, 0, "T000", "language/a.js"
                )

                self.assertEqual(status, "BUILD_ERROR")
                self.assertIn("does not match", reason)

    def test_pass_word_inside_failure_payload_cannot_override_verdict(self):
        cases = (
            (
                "T000 0.123s 456 CRASH Failure(PASS) language/a.js\n",
                "CRASH",
            ),
            (
                "T000 0.123s 456 UNSUPPORTED-EFFECT "
                "Take/UB; f PASS g language/a.js\n",
                "UNSUPPORTED",
            ),
            (
                "T000 0.123s 456 RESULT-DIFFERS "
                "language/a.js (VEnum PASS vs VBool)\n",
                "MISMATCH",
            ),
        )

        for output, expected in cases:
            with self.subTest(expected=expected):
                status, _ = runner.classify_driver_output(
                    output, 0, "T000", "language/a.js"
                )

                self.assertEqual(status, expected)

    def test_aggregate_is_sorted_by_global_index(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            results_dir = state_dir / "results"
            results_dir.mkdir()
            runner.write_result(
                results_dir,
                runner.Result(9, "z.js", "PASS", "run", 4, "000", 0.2, ""),
            )
            runner.write_result(
                results_dir,
                runner.Result(
                    2, "a.js", "ESMETA_FAILED", "export", 2, "-", 0.1, "boom"
                ),
            )

            selection = [
                runner.Target(0, 2, "a.js"),
                runner.Target(1, 9, "z.js"),
            ]
            runner.write_aggregate(state_dir, selection)

            rows = (state_dir / "results.tsv").read_text().splitlines()
            self.assertTrue(rows[1].startswith("2\t"))
            self.assertTrue(rows[2].startswith("9\t"))

    def test_multiple_runtime_jobs_are_accepted(self):
        args = runner.parse_args(["--jobs", "4", "--dry-run"])

        self.assertEqual(args.jobs, 4)
        self.assertEqual(args.export_jobs, 4)

    def test_export_jobs_can_be_tuned_independently(self):
        args = runner.parse_args(
            ["--jobs", "4", "--export-jobs", "12", "--dry-run"]
        )

        self.assertEqual(args.jobs, 4)
        self.assertEqual(args.export_jobs, 12)

    def test_native_worker_is_default_with_bytecode_fallback(self):
        self.assertEqual(
            runner.parse_args(["--dry-run"]).worker_mode,
            "native",
        )
        self.assertEqual(
            runner.parse_args(
                ["--dry-run", "--worker-mode", "bytecode"]
            ).worker_mode,
            "bytecode",
        )

    def test_payload_worker_build_uses_shared_build_lock(self):
        with tempfile.TemporaryDirectory() as directory:
            formal = Path(directory)
            executable = formal / "fvitree-worker-native"
            executable.touch()
            args = runner.parse_args(["--dry-run", "--jobs", "4"])
            result = runner.CommandResult(0, False, 0.1, "built")

            with mock.patch.object(runner, "FORMAL", formal), mock.patch.object(
                runner, "run_command", return_value=result
            ) as run_command:
                actual = runner.build_payload_worker(args, formal / "state")

            self.assertEqual(actual, executable)
            run_command.assert_called_once_with(
                [
                    "python3",
                    "./with-itree-build-lock.py",
                    "4",
                    "fvitree-worker-native",
                ],
                formal,
                args.build_timeout,
            )

    def test_run_command_pins_esmeta_home_to_runner_checkout(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory).resolve()
            command = [
                runner.sys.executable,
                "-c",
                "import os; print(os.environ['ESMETA_HOME'])",
            ]
            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.dict(
                    runner.os.environ,
                    {"ESMETA_HOME": "/different/checkout"},
                ),
            ):
                result = runner.run_command(command, root, 5)

            self.assertEqual(result.returncode, 0)
            self.assertFalse(result.timed_out)
            self.assertEqual(result.output.strip(), str(root))

    def test_persistent_exporter_command_starts_one_server(self):
        self.assertEqual(
            runner.persistent_exporter_command(
                "built-ins/Array", "/classes:/dependency.jar", 12
            ),
            [
                "java",
                "-Xms1g",
                "-Xmx8g",
                "-Xss4m",
                "-Dfile.encoding=utf8",
                "-cp",
                "/classes:/dependency.jar",
                "esmeta.fv.FVInitState",
                "--test262-server",
                "built-ins/Array",
                "--reuse-test262-base",
                "--payload-only",
                "--test262-export-jobs=12",
            ],
        )

    def test_extract_exporter_classpath_requires_existing_entries(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            classes = root / "classes"
            dependency = root / "dependency.jar"
            classes.mkdir()
            dependency.write_bytes(b"jar")
            classpath = runner.os.pathsep.join(
                (str(classes), str(dependency))
            )

            self.assertEqual(
                runner.extract_exporter_classpath(
                    f"[info] unrelated\n{classpath}\n"
                ),
                classpath,
            )
            with self.assertRaisesRegex(RuntimeError, "fullClasspath"):
                runner.extract_exporter_classpath("/missing:/also-missing\n")

    def test_exporter_protocol_ignores_sbt_prefix_and_ansi(self):
        line = "\x1b[32m[info]\x1b[0m FVEXPORT DONE 20 10 123"

        self.assertEqual(
            runner.parse_exporter_protocol(line),
            ["DONE", "20", "10", "123"],
        )
        self.assertIsNone(runner.parse_exporter_protocol("[info] compiling"))

    def test_persistent_exporter_sends_range_without_restarting_jvm(self):
        exporter = runner.PersistentExporter.__new__(
            runner.PersistentExporter
        )
        exporter.process = mock.MagicMock()
        exporter.process.poll.return_value = None
        exporter._read_protocol = mock.MagicMock(
            return_value=["DONE", "12", "34", "56"]
        )
        exporter._terminate = mock.MagicMock()
        exporter._spawn = mock.MagicMock()

        result = exporter.export(12, 34, 10)

        self.assertEqual(result.returncode, 0)
        exporter.process.stdin.write.assert_called_once_with("EXPORT 12 34\n")
        exporter.process.stdin.flush.assert_called_once_with()
        exporter._spawn.assert_not_called()
        exporter._terminate.assert_not_called()

    def test_checkpoint_does_not_rebuild_aggregate(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            result = runner.Result(
                7, "a.js", "PASS", "run", 0, "000", 0.1, ""
            )

            runner.checkpoint(state_dir, result)

            self.assertTrue((state_dir / "results" / "00007.tsv").exists())
            self.assertFalse((state_dir / "results.tsv").exists())

    def test_execute_routes_payload_through_persistent_worker_without_pass_log(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            payload = state_dir / "T000.fvt"
            payload.write_bytes(b"payload")
            args = runner.parse_args(["--dry-run"])
            workers = mock.MagicMock()
            workers.run.return_value = runner.CommandResult(
                0, False, 0.1, "T000 0.1s 1 PASS a.js\n"
            )

            result = runner.execute_emitted_test(
                runner.Target(0, 7, "a.js"),
                "000",
                payload,
                0,
                args,
                state_dir,
                workers,
            )

            self.assertEqual(result.status, "PASS")
            workers.run.assert_called_once_with(
                args.fuel,
                0,
                7,
                "a.js",
                payload,
                args.run_timeout,
            )
            self.assertFalse(
                (state_dir / "logs" / "run-00007.log").exists()
            )

    def test_execute_keeps_nonpass_worker_log(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            payload = state_dir / "T000.fvt"
            payload.write_bytes(b"payload")
            args = runner.parse_args(["--dry-run"])
            workers = mock.MagicMock()
            workers.run.return_value = runner.CommandResult(
                0,
                False,
                0.1,
                "T000 0.1s 1 UNSUPPORTED-EFFECT Choose a.js\n",
            )

            result = runner.execute_emitted_test(
                runner.Target(0, 7, "a.js"),
                "000",
                payload,
                0,
                args,
                state_dir,
                workers,
            )

            self.assertEqual(result.status, "UNSUPPORTED")
            log_path = state_dir / "logs" / "run-00007.log"
            self.assertTrue(log_path.is_file())
            self.assertIn("UNSUPPORTED-EFFECT", log_path.read_text())

    def test_default_shard_size_matches_full_run_profile(self):
        args = runner.parse_args(["--dry-run"])

        self.assertEqual(args.shard_size, 1280)

    def test_transient_export_failure_does_not_checkpoint_entire_shard(self):
        cases = (
            (runner.CommandResult(124, True, 1.0, "timeout"), "timed out"),
            (runner.CommandResult(1, False, 0.1, "protocol error"), "status 1"),
        )
        for export_result, expected_reason in cases:
            with self.subTest(expected_reason=expected_reason):
                with tempfile.TemporaryDirectory() as directory:
                    state_dir = Path(directory)
                    args = runner.parse_args(["--dry-run"])
                    exporter = mock.MagicMock()
                    exporter.export.return_value = export_result
                    group = [
                        runner.Target(0, 7, "a.js"),
                        runner.Target(1, 8, "b.js"),
                    ]

                    with self.assertRaisesRegex(RuntimeError, expected_reason):
                        runner.execute_range(
                            group,
                            args,
                            state_dir,
                            exporter,
                            mock.MagicMock(),
                        )

                    self.assertEqual(runner.read_results(state_dir / "results"), {})

    def test_payload_path_must_remain_inside_payload_directory(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory).resolve()
            payload_dir = root / "payload"
            payload_dir.mkdir()
            valid = payload_dir / "T000.fvt"
            valid.write_bytes(b"payload")

            with mock.patch.object(runner, "FORMAL", root), mock.patch.object(
                runner, "PAYLOAD_DIR", payload_dir
            ):
                self.assertEqual(
                    runner.resolve_payload_path("payload/T000.fvt"),
                    valid,
                )
                with self.assertRaisesRegex(ValueError, "escapes"):
                    runner.resolve_payload_path("../outside.fvt")

    def test_campaign_rejects_reusing_state_for_another_selection(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            args = runner.parse_args(["--dry-run", "--fuel", "100"])
            first = [runner.Target(0, 7, "a.js")]
            second = [runner.Target(0, 8, "b.js")]

            runner.ensure_campaign(state_dir, first, args, "same-source")

            with self.assertRaises(RuntimeError):
                runner.ensure_campaign(state_dir, second, args, "same-source")

    def test_campaign_resumes_with_identical_source_fingerprint(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            args = runner.parse_args(["--dry-run"])
            selection = [runner.Target(0, 7, "a.js")]

            runner.ensure_campaign(state_dir, selection, args, "stable")
            runner.ensure_campaign(state_dir, selection, args, "stable")

    def test_campaign_rejects_changed_execution_policy(self):
        selection = [runner.Target(0, 7, "a.js")]
        changed_options = (
            ("--shard-size", "21"),
            ("--jobs", "2"),
            ("--export-jobs", "2"),
            ("--fuel", "200"),
            ("--export-timeout", "10"),
            ("--build-timeout", "20"),
            ("--run-timeout", "30"),
            ("--worker-mode", "bytecode"),
        )

        for option, value in changed_options:
            with self.subTest(option=option), tempfile.TemporaryDirectory() as directory:
                state_dir = Path(directory)
                original = runner.parse_args(["--dry-run"])
                changed = runner.parse_args(["--dry-run", option, value])

                runner.ensure_campaign(state_dir, selection, original, "stable")

                with self.assertRaisesRegex(
                    RuntimeError, "different campaign"
                ):
                    runner.ensure_campaign(
                        state_dir, selection, changed, "stable"
                    )

    def test_campaign_rejects_changed_source_fingerprint(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            args = runner.parse_args(["--dry-run"])
            selection = [runner.Target(0, 7, "a.js")]

            runner.ensure_campaign(state_dir, selection, args, "before")

            with self.assertRaisesRegex(
                RuntimeError, "source fingerprint changed"
            ):
                runner.ensure_campaign(state_dir, selection, args, "after")

    def test_source_drift_quarantines_campaign_permanently(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            args = runner.parse_args(["--dry-run"])
            selection = [runner.Target(0, 7, "a.js")]
            runner.ensure_campaign(state_dir, selection, args, "before")

            with mock.patch.object(
                runner, "source_fingerprint", return_value="after"
            ):
                with self.assertRaisesRegex(
                    RuntimeError, "source changed"
                ):
                    runner.ensure_source_unchanged(
                        state_dir, "before", "after shard execution"
                    )

            drift = json.loads(
                (state_dir / "source-drift.json").read_text(
                    encoding="utf-8"
                )
            )
            self.assertEqual(drift["expectedSourceSha256"], "before")
            self.assertEqual(drift["actualSourceSha256"], "after")

            with self.assertRaisesRegex(
                RuntimeError, "invalidated by source drift"
            ):
                runner.ensure_campaign(
                    state_dir, selection, args, "before"
                )

    def test_campaign_rejects_old_metadata_without_source_identity(self):
        with tempfile.TemporaryDirectory() as directory:
            state_dir = Path(directory)
            args = runner.parse_args(["--dry-run"])
            selection = [runner.Target(0, 7, "a.js")]
            (state_dir / "campaign.json").write_text(
                json.dumps({"version": 1}), encoding="utf-8"
            )

            with self.assertRaisesRegex(RuntimeError, "metadata is obsolete"):
                runner.ensure_campaign(
                    state_dir, selection, args, "current"
                )

    def test_result_with_foreign_global_index_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            results_dir = Path(directory)
            runner.write_result(
                results_dir,
                runner.Result(8, "b.js", "PASS", "run", 0, "000", 0.1, ""),
            )

            with self.assertRaisesRegex(
                RuntimeError, "does not belong to this campaign"
            ):
                runner.read_results(
                    results_dir, [runner.Target(0, 7, "a.js")]
                )

    def test_result_with_wrong_name_for_global_index_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            results_dir = Path(directory)
            runner.write_result(
                results_dir,
                runner.Result(7, "wrong.js", "PASS", "run", 0, "000", 0.1, ""),
            )

            with self.assertRaisesRegex(
                RuntimeError, "does not belong to this campaign"
            ):
                runner.read_results(
                    results_dir, [runner.Target(0, 7, "a.js")]
                )

    def test_manifest_requires_matching_index_and_name(self):
        group = [runner.Target(0, 7, "a.js")]
        rows = [
            {
                "globalIndex": "7",
                "localModuleIndex": "000",
                "relName": "wrong.js",
                "disposition": "EMITTED",
                "reason": "",
            }
        ]

        with self.assertRaisesRegex(ValueError, "path does not match"):
            runner.validate_manifest(rows, group)

    def test_manifest_rejects_foreign_global_index(self):
        group = [runner.Target(0, 7, "a.js")]
        rows = [
            {
                "globalIndex": "8",
                "localModuleIndex": "000",
                "relName": "a.js",
                "disposition": "EMITTED",
                "reason": "",
            }
        ]

        with self.assertRaisesRegex(ValueError, "indices do not match"):
            runner.validate_manifest(rows, group)

    def test_dry_run_bootstraps_inventory_before_loading_it(self):
        events = []
        target = runner.Target(0, 7, "a.js")

        def bootstrap(_args):
            events.append("bootstrap")
            return "source"

        def load(_path, _prefix):
            self.assertEqual(events, ["bootstrap"])
            events.append("load")
            return [target]

        with tempfile.TemporaryDirectory() as directory:
            with (
                mock.patch.object(runner, "bootstrap_inventory", bootstrap),
                mock.patch.object(runner, "load_inventory", load),
                mock.patch.object(
                    runner, "source_fingerprint", return_value="source"
                ),
                mock.patch.object(runner, "RunLock", mock.MagicMock()),
                mock.patch.object(runner, "ensure_campaign") as ensure,
                mock.patch.object(runner, "read_results", return_value={}),
            ):
                result = runner.main(
                    [
                        "--dry-run",
                        "--state-dir",
                        str(Path(directory) / "state"),
                    ]
                )

        self.assertEqual(result, 0)
        self.assertEqual(events, ["bootstrap", "load"])
        self.assertFalse(ensure.call_args.kwargs["create"])

    def test_bootstrap_reuses_only_matching_stamped_base(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            inventory.write_text("inventory\n", encoding="utf-8")
            stamp.write_text(
                json.dumps(
                    {
                        "version": 1,
                        "sourceSha256": "current",
                        "inventorySha256": runner.file_sha256(inventory),
                    }
                ),
                encoding="utf-8",
            )
            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner, "source_fingerprint", return_value="current"
                ),
                mock.patch.object(runner, "run_command") as run,
            ):
                fingerprint = runner.bootstrap_inventory(
                    runner.parse_args(["--dry-run"])
                )

            self.assertEqual(fingerprint, "current")
            run.assert_not_called()

    def test_bootstrap_regenerates_when_base_stamp_is_stale(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            inventory.write_text("inventory\n", encoding="utf-8")
            stamp.write_text(
                json.dumps(
                    {
                        "version": 1,
                        "sourceSha256": "old",
                        "inventorySha256": runner.file_sha256(inventory),
                    }
                ),
                encoding="utf-8",
            )
            command = []

            def run(actual, _cwd, _timeout):
                command.extend(actual)
                return runner.CommandResult(0, False, 0.1, "")

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner,
                    "source_fingerprint",
                    side_effect=["before", "after"],
                ),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    return_value="stable-inputs",
                ),
                mock.patch.object(runner, "run_command", side_effect=run),
            ):
                fingerprint = runner.bootstrap_inventory(
                    runner.parse_args(["--dry-run"])
                )

            self.assertEqual(fingerprint, "after")
            self.assertNotIn("--reuse-test262-base", command[1])
            saved = json.loads(stamp.read_text(encoding="utf-8"))
            self.assertEqual(saved["sourceSha256"], "after")

    def test_bootstrap_regenerates_partial_spec_closure_before_stamping(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            (validation / "spec" / "SpecHeap_0000.v").unlink()
            events = []

            def initialize(_command, _cwd, _timeout):
                events.append("FVInitState")
                self.write_generated_semantic_fixture(root)
                inventory.write_text("inventory\n", encoding="utf-8")
                return runner.CommandResult(0, False, 0.1, "")

            def fingerprint():
                events.append("fingerprint")
                return "regenerated"

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(runner, "source_fingerprint", fingerprint),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    return_value="stable-inputs",
                ),
                mock.patch.object(runner, "run_command", initialize),
            ):
                actual = runner.bootstrap_inventory(
                    runner.parse_args(["--dry-run"])
                )

            self.assertEqual(events, ["FVInitState", "fingerprint"])
            self.assertEqual(actual, "regenerated")
            saved = json.loads(stamp.read_text(encoding="utf-8"))
            self.assertEqual(saved["sourceSha256"], "regenerated")

    def test_bootstrap_regenerates_malformed_spec_closure(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            (validation / "SpecSources.mk").write_text(
                "interrupted write\n", encoding="utf-8"
            )

            def initialize(_command, _cwd, _timeout):
                self.write_generated_semantic_fixture(root)
                inventory.write_text("inventory\n", encoding="utf-8")
                return runner.CommandResult(0, False, 0.1, "")

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner,
                    "source_fingerprint",
                    return_value="regenerated",
                ),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    return_value="stable-inputs",
                ),
                mock.patch.object(
                    runner, "run_command", side_effect=initialize
                ) as run_command,
            ):
                runner.bootstrap_inventory(runner.parse_args(["--dry-run"]))

            run_command.assert_called_once()

    def test_bootstrap_recovers_from_malformed_stamp_json(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            inventory.write_text("inventory\n", encoding="utf-8")
            stamp.write_text("{not json\n", encoding="utf-8")

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner,
                    "source_fingerprint",
                    return_value="current",
                ),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    return_value="stable-inputs",
                ),
                mock.patch.object(
                    runner,
                    "run_command",
                    return_value=runner.CommandResult(0, False, 0.1, ""),
                ),
            ):
                runner.bootstrap_inventory(runner.parse_args(["--dry-run"]))

            saved = json.loads(stamp.read_text(encoding="utf-8"))
            self.assertEqual(saved["sourceSha256"], "current")

    def test_bootstrap_surfaces_stamp_read_oserror(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            inventory.write_text("inventory\n", encoding="utf-8")
            stamp = mock.MagicMock(spec=Path)
            stamp.is_file.return_value = True
            stamp.read_text.side_effect = PermissionError("stamp denied")

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner,
                    "source_fingerprint",
                    return_value="current",
                ),
                mock.patch.object(runner, "run_command") as run_command,
                self.assertRaisesRegex(PermissionError, "stamp denied"),
            ):
                runner.bootstrap_inventory(runner.parse_args(["--dry-run"]))

            run_command.assert_not_called()

    def test_bootstrap_rejects_generator_input_drift_without_stamping(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            inventory.write_text("inventory\n", encoding="utf-8")

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    side_effect=["before", "after"],
                ),
                mock.patch.object(
                    runner,
                    "source_fingerprint",
                    return_value="mixed-output",
                ),
                mock.patch.object(
                    runner,
                    "run_command",
                    return_value=runner.CommandResult(0, False, 0.1, ""),
                ),
                self.assertRaisesRegex(RuntimeError, "inputs changed"),
            ):
                runner.bootstrap_inventory(runner.parse_args(["--dry-run"]))

            self.assertFalse(stamp.exists())

    def test_bootstrap_generates_missing_spec_before_fingerprinting(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            validation = root / "formal" / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            (validation / "Spec.v").unlink()
            (validation / "SpecSources.mk").unlink()
            for path in (validation / "spec").iterdir():
                path.unlink()
            events = []

            def initialize(_command, _cwd, _timeout):
                events.append("FVInitState")
                self.write_generated_semantic_fixture(root)
                inventory.write_text("inventory\n", encoding="utf-8")
                return runner.CommandResult(0, False, 0.1, "")

            def fingerprint():
                events.append("fingerprint")
                return "regenerated"

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", root / "formal"),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(runner, "source_fingerprint", fingerprint),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    return_value="stable-inputs",
                ),
                mock.patch.object(runner, "run_command", initialize),
            ):
                runner.bootstrap_inventory(runner.parse_args(["--dry-run"]))

            self.assertEqual(events, ["FVInitState", "fingerprint"])

    def test_bootstrap_stamps_fingerprint_regenerated_from_missing_spec(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            validation = root / "formal" / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            (validation / "Spec.v").unlink()
            (validation / "SpecSources.mk").unlink()
            for path in (validation / "spec").iterdir():
                path.unlink()

            def initialize(_command, _cwd, _timeout):
                self.write_generated_semantic_fixture(root)
                inventory.write_text("inventory\n", encoding="utf-8")
                return runner.CommandResult(0, False, 0.1, "")

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", root / "formal"),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(
                    runner,
                    "source_fingerprint",
                    return_value="regenerated",
                ),
                mock.patch.object(
                    runner,
                    "generator_input_fingerprint",
                    return_value="stable-inputs",
                ),
                mock.patch.object(runner, "run_command", initialize),
            ):
                fingerprint = runner.bootstrap_inventory(
                    runner.parse_args(["--dry-run"])
                )

            self.assertEqual(fingerprint, "regenerated")
            saved = json.loads(stamp.read_text(encoding="utf-8"))
            self.assertEqual(saved["sourceSha256"], "regenerated")

    def test_bootstrap_rejects_missing_tymodel_source(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            formal = root / "formal"
            validation = formal / "validation"
            inventory = validation / "test262-inventory.tsv"
            stamp = validation / "test262-base.json"
            (formal / "TyModel.v").unlink()
            (validation / "Spec.v").unlink()
            (validation / "SpecSources.mk").unlink()
            for path in (validation / "spec").iterdir():
                path.unlink()

            with (
                mock.patch.object(runner, "ROOT", root),
                mock.patch.object(runner, "FORMAL", formal),
                mock.patch.object(runner, "INVENTORY", inventory),
                mock.patch.object(runner, "BASE_STAMP", stamp),
                mock.patch.object(runner, "run_command") as run_command,
                self.assertRaisesRegex(RuntimeError, "TyModel"),
            ):
                runner.bootstrap_inventory(runner.parse_args(["--dry-run"]))

            run_command.assert_not_called()

    def test_source_fingerprint_is_stable_and_tracks_dirty_inputs(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            runner_file = root / "formal" / "run-test262-full.py"
            runner_file.write_text("version = 1\n", encoding="utf-8")
            semantic_file = root / "formal" / "Fragment.v"
            semantic_file.write_text("Definition semantic := 1.\n", encoding="utf-8")
            proof_file = root / "formal" / "SpecAssertionProof.v"
            proof_file.write_text("Theorem proof_only : True.\n", encoding="utf-8")
            validation_only_files = (
                root / "formal" / "Exec.v",
                root / "formal" / "modular_driver.ml",
                root / "formal" / "gen-extract-shard.sh",
            )
            for path in validation_only_files:
                path.write_text("validation only\n", encoding="utf-8")
            resource_file = (
                root
                / "src"
                / "main"
                / "resources"
                / "manuals"
                / "funcs"
                / "HostSemantic.ir"
            )
            resource_file.parent.mkdir(parents=True)
            resource_file.write_text("semantic resource one\n", encoding="utf-8")
            extensionless_resource = resource_file.parents[1] / "intrinsics"
            extensionless_resource.write_text(
                "extensionless semantic resource\n", encoding="utf-8"
            )
            for relative in runner.SUBMODULE_PATHS:
                repository = root / relative
                repository.mkdir(parents=True)
                subprocess.run(
                    ["git", "init", "-q"], cwd=repository, check=True
                )
                subprocess.run(
                    ["git", "config", "user.email", "test@example.com"],
                    cwd=repository,
                    check=True,
                )
                subprocess.run(
                    ["git", "config", "user.name", "Test"],
                    cwd=repository,
                    check=True,
                )
                tracked = repository / "tracked.js"
                tracked.write_text("one\n", encoding="utf-8")
                subprocess.run(
                    ["git", "add", "tracked.js"], cwd=repository, check=True
                )
                subprocess.run(
                    ["git", "commit", "-qm", "fixture"],
                    cwd=repository,
                    check=True,
                )

            first = runner.source_fingerprint(root)
            self.assertEqual(first, runner.source_fingerprint(root))

            proof_file.write_text(
                "Theorem proof_only : True. Proof. exact I. Qed.\n",
                encoding="utf-8",
            )
            self.assertEqual(first, runner.source_fingerprint(root))

            for path in validation_only_files:
                path.write_text("changed validation only\n", encoding="utf-8")
            self.assertEqual(first, runner.source_fingerprint(root))

            resource_file.write_text(
                "semantic resource two\n", encoding="utf-8"
            )
            resource_changed = runner.source_fingerprint(root)
            self.assertNotEqual(first, resource_changed)
            campaign_dir = root / "campaign"
            selection = [runner.Target(0, 7, "resource-sensitive.js")]
            args = runner.parse_args(["--dry-run"])
            runner.ensure_campaign(campaign_dir, selection, args, first)
            with self.assertRaisesRegex(
                RuntimeError, "source fingerprint changed"
            ):
                runner.ensure_campaign(
                    campaign_dir, selection, args, resource_changed
                )

            extensionless_resource.write_text(
                "changed extensionless semantic resource\n", encoding="utf-8"
            )
            extensionless_changed = runner.source_fingerprint(root)
            self.assertNotEqual(resource_changed, extensionless_changed)

            semantic_file.write_text(
                "Definition semantic := 2.\n", encoding="utf-8"
            )
            semantic_changed = runner.source_fingerprint(root)
            self.assertNotEqual(extensionless_changed, semantic_changed)

            runner_file.write_text("version = 2\n", encoding="utf-8")
            second = runner.source_fingerprint(root)
            self.assertNotEqual(semantic_changed, second)

            dirty = root / runner.SUBMODULE_PATHS[-1] / "tracked.js"
            dirty.write_text("two\n", encoding="utf-8")
            self.assertNotEqual(second, runner.source_fingerprint(root))

    def test_source_fingerprint_tracks_generated_semantic_closure_only(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            for relative in runner.SUBMODULE_PATHS:
                repository = root / relative
                repository.mkdir(parents=True)
                subprocess.run(["git", "init", "-q"], cwd=repository, check=True)
                subprocess.run(
                    ["git", "config", "user.email", "test@example.com"],
                    cwd=repository,
                    check=True,
                )
                subprocess.run(
                    ["git", "config", "user.name", "Test"],
                    cwd=repository,
                    check=True,
                )
                (repository / "tracked.js").write_text("one\n", encoding="utf-8")
                subprocess.run(
                    ["git", "add", "tracked.js"], cwd=repository, check=True
                )
                subprocess.run(
                    ["git", "commit", "-qm", "fixture"],
                    cwd=repository,
                    check=True,
                )

            first = runner.source_fingerprint(root)
            binding = root / "formal" / "TyModelBindings00.v"
            binding.write_text("Definition bindings := 2.\n", encoding="utf-8")
            tymodel_changed = runner.source_fingerprint(root)
            self.assertNotEqual(first, tymodel_changed)

            shard = root / "formal" / "validation" / "spec" / "SpecHeap_0000.v"
            shard.write_text("(* changed semantic shard *)\n", encoding="utf-8")
            changed = runner.source_fingerprint(root)
            self.assertNotEqual(tymodel_changed, changed)

            spec_manifest = root / "formal" / "validation" / "SpecSources.mk"
            spec_manifest.write_text(
                spec_manifest.read_text(encoding="utf-8").replace(
                    "  validation/spec/SpecHeap_0000.v\n",
                    "  validation/spec/SpecHeap_0000.v \\\n"
                    "  validation/spec/SpecHeap_0001.v\n",
                ),
                encoding="utf-8",
            )
            (shard.parent / "SpecHeap_0001.v").write_text(
                "(* newly manifested semantic shard *)\n", encoding="utf-8"
            )
            (shard.parent / "SpecHeap.v").write_text(
                "From ESMetaFV.validation.spec Require Export "
                "SpecHeap_0000 SpecHeap_0001.\n",
                encoding="utf-8",
            )
            expanded = runner.source_fingerprint(root)
            self.assertNotEqual(changed, expanded)

            (shard.parent / "SpecHeap_0000.vo").write_text(
                "ephemeral\n", encoding="utf-8"
            )
            (root / "formal" / "logs").mkdir()
            (root / "formal" / "logs" / "run.log").write_text(
                "log\n", encoding="utf-8"
            )
            self.assertEqual(expanded, runner.source_fingerprint(root))

            coq_project = root / "formal" / "_CoqProject"
            coq_project.write_text(
                "another-unrelated-proof.v\n"
                + "\n".join(
                    [
                        runner.TYMODEL_BLOCK_START,
                        "TyModelBase.v",
                        "TyModelParent00.v",
                        "TyModelBindings00.v",
                        "TyModel.v",
                        runner.TYMODEL_BLOCK_END,
                    ]
                )
                + "\n",
                encoding="utf-8",
            )
            self.assertEqual(expanded, runner.source_fingerprint(root))

    def test_generated_semantic_closure_fails_fast_on_missing_or_drift(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self.write_generated_semantic_fixture(root)
            missing = root / "formal" / "TyModelParent00.v"
            missing.unlink()
            with self.assertRaisesRegex(RuntimeError, "closure is incomplete"):
                runner._generated_semantic_sources(root)

            self.write_generated_semantic_fixture(root)
            facade = root / "formal" / "TyModel.v"
            facade.write_text(
                "From ESMetaFV Require Import TyModelBase.\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(RuntimeError, "does not match"):
                runner._generated_semantic_sources(root)

            self.write_generated_semantic_fixture(root)
            manifest = root / "formal" / "validation" / "SpecSources.mk"
            manifest.write_text("malformed\n", encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "manifest is malformed"):
                runner._generated_semantic_sources(root)

            self.write_generated_semantic_fixture(root)
            spec_facade = (
                root / "formal" / "validation" / "spec" / "SpecFuncs.v"
            )
            spec_facade.write_text(
                "From ESMetaFV.validation.spec Require Export "
                "SpecFuncs_0000 SpecFuncs_0001.\n",
                encoding="utf-8",
            )
            with self.assertRaisesRegex(RuntimeError, "facade does not match"):
                runner._generated_semantic_sources(root)


if __name__ == "__main__":
    unittest.main()
